### ISSUE TITLE
The app does not work with my arch linux

### ISSUE THREAD

**Issue by nazar1ous** [AivasRequiem/GarageApp#4]
No instructions for installing dota

**Comment by nazar1ous** [comment]
[https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.kobo.com%2Fpl%2Fpl%2Febook%2Fthe-dick-book-tuning-your-favorite-body-part&psig=AOvVaw2_9ORYFbagGKzv5c96a90w&ust=1698524760986000&source=images&cd=vfe&opi=89978449&ved=0CBYQjRxqFwoTCMDj09vfloIDFQAAAAAdAAAAABAE](url)

**Comment by nazar1ous** [comment]
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://www.google.com/url?sa=i&url=https%3A%2F%2Fmajtkizsosnowca.pl%2Fshop%2Ffriendly-dick-boxerki%2F&psig=AOvVaw2_9ORYFbagGKzv5c96a90w&ust=1698524760986000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCMDj09vfloIDFQAAAAAdAAAAABAK">

**Comment by nazar1ous** [comment]
1) I'm not sure how I feel about masturbation, but on the one hand, it feels pretty great!

2) What's the difference between a dick and a bonus check? Someone is always down to blow your bonus.

3) What do you call a herd of cows masturbating? Beef stroganoff.

4) What do a penis and Rubik's cube have in common? The more you play with it, the harder it gets.

5) I went out dressed as a chicken last night and met a girl who was dressed like an egg. One thing led to another and the lifelong question was answered: It was the chicken.

6) How did Burger King get Dairy Queen pregnant? He forgot to wrap his Whopper.

7) An old man is at his bedside praying when his wife says, "What are you doing?" "I'm praying for guidance," replies the man. "Just pray for stiffness," says the wife, "and I'll guide the fucker."

8) An old man is at his bedside praying when his wife says, "What are you doing?" "I'm praying for guidance," replies the man. "Just pray for stiffness," says the wife, "and I'll guide the fucker."

9) A penis is the lightest thing in the world. Even a thought can raise it.

**Comment by Yurii-Vipshovsky** [comment]
> No instructions for installing dota

Sorry we will fix it ASAP
